spring.application.name=airBnbApp

# Database configuration

# Database configuration

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA and Hibernate configuration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#API documentation configuration

server.servlet.context-path=/api/v1
server.port=${PORT:8080}

#SWAGGER CONFIGURATION

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#JWT CONFIGURATION

jwt.secretKey=${JWT_SECRET}


#FRONTEND CONFIGURATION
#// this is the url of the front end application which is running on port 3000 and now iam doing it only backendfrontend
frontend.url=${FRONTEND_URL:http://localhost:8080}


#//stripe.api.key=sk_test_51N0g6pSFX1 this is temporary key for stripe payment gateway and it will be changed in future
stripe.secret.key=${STRIPE_SECRET_KEY:}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:}




